name: smart_trash_bin_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase dependencies
  firebase_core: ^3.0.0
  firebase_database: ^11.0.0
  # Local notifications
  flutter_local_notifications: ^17.0.0
  # Toast notifications
  fluttertoast: ^8.2.4
  # Permission handler
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
